"""GET /orders endpoint - deliberately slow. Do not edit this file.

Write a fixed version in optimized.py (see the task instructions). Each
function below stands in for a real database call that costs a network round
trip; every call is one query against the "database".
"""

from flask import Flask, jsonify, request

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Fake in-memory "database". 50 customers, 500 orders, 5000 line items.
# NOTE: there is no index on orders.customer_id or order_items.order_id -
# every lookup below scans the whole table.
# ---------------------------------------------------------------------------

ORDERS = [
    {
        "id": i,
        "customer_id": (i % 100) + 1,
        "status": "paid",
        "created_at": f"2026-01-{i % 28 + 1:02d}",
    }
    for i in range(1, 501)
]

ORDER_ITEMS = [
    {"id": k, "order_id": (k % 500) + 1, "product_id": k % 40, "qty": (k % 3) + 1}
    for k in range(1, 5001)
]


def get_orders(customer_id):
    """SELECT * FROM orders WHERE customer_id = ?  (full table scan - no index)."""
    return [o for o in ORDERS if o["customer_id"] == customer_id]


def fetch_items(order_id):
    """SELECT * FROM order_items WHERE order_id = ?  (one round trip per call)."""
    return [i for i in ORDER_ITEMS if i["order_id"] == order_id]


def get_orders_with_items(customer_id):
    """1 query for the orders, then ONE query PER ORDER for its items = N+1."""
    orders = get_orders(customer_id)  # query #1
    for order in orders:  # N more queries - one per order
        order["items"] = fetch_items(order["id"])
    return orders


@app.get("/orders")
def list_orders():
    """Slow endpoint: a customer with ~50 orders triggers ~51 queries, and each
    lookup scans the whole table because the lookup columns are not indexed.
    There is no caching, so every request repeats all of it."""
    customer_id = int(request.args.get("customer_id"))
    return jsonify(get_orders_with_items(customer_id))
